jwt:
  base64-secret: YXNqaGR2ZnZ1Y2dpZWY3ODIzdWlyZ2Y3dDRyYmd2NzIzZ3QwcTlnaWJIQVU5ODY5aDB1Z2c5OUc5djc3OGdHNzdoeUc4N3Y4OE5iODZFY2NkRkY1ZnZ2QzZWcjY2UjY1UjZ2NXY1N2J2VUlHOTg2Rzc4VGg3OD09
  token-validity: 86400
